# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QuickGo < Formula
  desc "Golang quick start."
  homepage "https://github.com/maguowei/quick-go"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maguowei/quick-go/releases/download/v0.3.3/quick-go_0.3.3_Darwin_arm64.tar.gz"
      sha256 "dea5382658c2b91b44f86b41828ae7d34a2d9eb73781d6a0b03da46004615363"

      def install
        bin.install "quick-go"
        ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maguowei/quick-go/releases/download/v0.3.3/quick-go_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "c186cbb4c937fd0cd188f8a379cc16dce72d551d88872718646151bd92f54912"

      def install
        bin.install "quick-go"
        ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maguowei/quick-go/releases/download/v0.3.3/quick-go_0.3.3_Linux_x86_64.tar.gz"
      sha256 "6831735b7ef4c02fdc1289ea540d2c24e8bdea19f35011947cd0c8a7bce100f3"

      def install
        bin.install "quick-go"
        ...
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maguowei/quick-go/releases/download/v0.3.3/quick-go_0.3.3_Linux_arm64.tar.gz"
      sha256 "0f524a9ff8c5c88c9014662136fce63632e233b81ce3b1994f075b2c488caead"

      def install
        bin.install "quick-go"
        ...
      end
    end
  end

  test do
    system "#{bin}/quick-go --version"
    ...
  end
end
