# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QuickGo < Formula
  desc "Golang quick start."
  homepage "https://github.com/maguowei/quick-go"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maguowei/quick-go/releases/download/v0.4.0/quick-go_0.4.0_Darwin_arm64.tar.gz"
      sha256 "5fdc4fd9aedcaa53bf6e25f752c799f6d149fe05f7b6db59b75116ef98c5293d"

      def install
        bin.install "quick-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maguowei/quick-go/releases/download/v0.4.0/quick-go_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "d0ee975a9f023c8660d052417ade4b651545d904b36765695680ceea903fb9e6"

      def install
        bin.install "quick-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maguowei/quick-go/releases/download/v0.4.0/quick-go_0.4.0_Linux_x86_64.tar.gz"
      sha256 "92a96143a3f86e3ac117cb43b3d308e1b9ec6ca50f58ce71e35e3ee1d0d27be8"

      def install
        bin.install "quick-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maguowei/quick-go/releases/download/v0.4.0/quick-go_0.4.0_Linux_arm64.tar.gz"
      sha256 "3599b84d3b86a187a0aaa1f5c96bdf24b91f06776ca51dd9bab7407db3e2c327"

      def install
        bin.install "quick-go"
      end
    end
  end

  test do
    system "#{bin}/quick-go --version"
  end
end
